### ISSUE TITLE
raise SignatureError.new "Actual: #{signature_header}, Expected: #{expected_signature}"

### ISSUE THREAD

**Issue by pvin** [ssaunier/trello_webhook#1]
Hi im using this gem along with ruby-trello.

I am not sure it is an issue but stuck with this error called
 '   TrelloWebhook::Processor::SignatureError (Actual: 1knsl9DCwI+RJ2H2u4ewffGLrTA=, Expected: 5X4u17avdb45tb3ktjoZNNzKCjo=)   ' 

Any idea that what I did wrong to get this error??

**Comment by ssaunier** [comment]
Hi @pvin,

Make sure that you return the correct string in the `TrelloWebhooksController#webhook_secret` method. If you're confused, that should be the OAuth 1 secret at the bottom of the page https://trello.com/app-key

I advise you store this variable in the environment like in the README example.

I use this gem myself and I don't have this error, the webhook signature matches the one I compute. Do not hesitate to start from scratch, deleting the webhook and creating a new one. Also make sure your environment in production does have the trello secret.

**Comment by pvin** [comment]
@ssaunier 
Thanks for a quick response.

**Comment by pvin** [comment]
@ssaunier  Thanks a lot.
Problem is key. Key was given instead of Secret.
